#############################################################################################
### when local deployed with vscode launch or npm run
@local=http://localhost:8888/.netlify/functions/
@now = {{$datetime iso8601}}

###
GET {{local}}/test

###
GET  {{local}}/testcrypto?id=FBOZDXIs7GU%2B0fuBsKRzM7sSyaFO%2BHLM2erHJa5bxBkDRttD3dUCmKyDDu8kcur3qOP1%2BArVy%2BRftwZFzOgguShU33VpimmiaqZOxCbrJAI%3D

###
GET {{local}}/testsqlite

###
POST {{local}}/testcrypto
content-type: application/json

{
    "ID": "C07",
    "nom": "LOPEZ",
    "boia": 29,
    "matricula": "8088GMD"
}


###
POST {{local}}/testsqlite
content-type: application/json

{
  "name": "pithing",
  "value": "3.14"
}

###
GET {{local}}/testsqlite?id=1


###
GET {{local}}/testsqlite?id=1

###
GET {{local}}/qrcodes?id=12341234

###
POST {{local}}/qrcodes
content-type: application/json

{
  "name": "something",
  "value": "42"
}

###
POST {{local}}/qrcodes
Accept: text/html
content-type: application/json

{
  "name": "something",
  "value": 42
}


###
POST {{local}}/qrcodes
Accept: image/png
content-type: application/json

{
  "name": "something",
  "value": 42
}

###
POST {{local}}/qrcodes
Accept: application/pdf
content-type: application/json

{
  "name": "something",
  "value": 42
}

###
GET {{local}}/qrcodes?id=SS%2BCtowjNBrtfcxuIgfVHJwB49sBCBu8WqiLnTABqzY4tZztav%2BgHG5%2FQlATA%2F1y


###
GET {{local}}/qrcodes?id=SS%2BCtowjNBrtfcxuIgfVHJwB49sBCBu8WqiLnTABqzY4tZztav%2BgHG5%2FQlATA%2F1y
Accept: text/html

###
GET {{local}}/qrcodes?id=SS%2BCtowjNBrtfcxuIgfVHJwB49sBCBu8WqiLnTABqzY4tZztav%2BgHG5%2FQlATA%2F1y
Accept: text/plain



#############################################################################################
@remote=https://citas-celebres-ji.netlify.app/.netlify/functions

### after deploy to netlify via push to github
GET  {{remote}}/testcrud

###
GET {{remote}}/citas

###
GET {{remote}}/citas
Accept: text/html

###
GET {{remote}}/citas
Accept: application/json

###
GET {{remote}}/citas?random=true
Accept: application/json

###
POST  {{remote}}/testcrud
content-type: application/json

{
    "name": "R2D2"
}


###
GET {{remote}}/testcrypto?id=1TRC2HyY9NT6RVNO7ZahU3Tod9RlKUoD8M0k77W8q9K3TaBn5fS0FRkY9GRRPBgAK6bSZsOaOgxtfhLjf3sihRWVfJnuXCAjSJmXvYt7%2BzOZTYMEVfSgI1g%2BnVj2U3Mt


###
POST {{remote}}/testcrypto
content-type: application/json

{
    "ID": "C42",
    "nom": "SMITH",
    "boia": 12,
    "matricula": "9876FGH"
}


###
GET {{remote}}/testsqlite?id=1

###
POST {{remote}}/testsqlite
content-type: application/json

{
  "name": "something",
  "value": "42"
}

###
GET {{remote}}/qrcodes?id=SS%2BCtowjNBrtfcxuIgfVHJwB49sBCBu8WqiLnTABqzY4tZztav%2BgHG5%2FQlATA%2F1y
Accept: text/plain
